### ISSUE TITLE
Formalising the workflow

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/SACRO-ML#1]
Below is a draft of the current workflow for programmatically running the AI-SDC attacks (adapted from the lira example). We should edit this and decide on the correct workflow for the whole process. 

---

**Researcher:**
1. Partitions their data into training and testing subsets.
2. Trains their model.
3. Wraps the data into a Data object (providing encoding information etc. as necessary).
4. Provides the model and Data to the TRE.

**TRE:**
1. Creates an attack object and calls the attack code.
2. Computes and inspects attack metrics.

---

With the *safemodel* wrapper:

**Researcher:**
1. Partitions their data into training and testing subsets.
2. Creates a safemodel and trains it.
3. Wraps the data into a Data object (providing encoding information etc. as necessary).
4. Calls the `run_attack()` code on the safemodel, specifying which attack to run.
5. Computes and inspects attack metrics.
6. Provides the JSON output to the TRE for inspection.

**TRE:**
1. Reads the JSON output and applies risk appetite rules.

---

At the moment the *safemodel* wrapper attacks to run are specified separately (for example, as below); in order to do things like failing fast do we need an "all" option? There is also the situation where a researcher trains a few different models with different hyperparameters and then wishes to see which of those pass the disclosure tests so they can pick the highest accuracy one that satisfies the requirements?

```python
for attack_name in ["worst_case", "attribute", "lira"]:
        fname = f"attack_output_{attack_name}"
        metadata = model.run_attack(the_data, attack_name, fname)
```

**Comment by jim-smith** [comment]
At the moment if they use the safemodel wrapper approach, they end by calling 'request Release().

That generates the json file, and in the process of doing that it currently runs all the attacks
